import { Poppins } from "next/font/google";
import "./globals.css";
import { ProgressBar } from "./components";
import { getProfile } from "@/services";
import Head from "next/head";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({ children }) {
  const dataProfile = await getProfile();
  return (
    <html lang="en" data-theme="light">
      <head>
        <link rel="icon" href="/mci.webp" />
        <meta name="keywords" content={`${dataProfile?.data?.name}`} />
        <meta name="google-site-verification" content="MKGqUo41qxOGPMhfXIIk5bHmdzYcJwG__yzDU8dyxlM" />
        <meta name="description" content={dataProfile?.data?.about_us} />
      </head>
      <body className={poppins.className}>
        <ProgressBar />
        {children}
      </body>
    </html>
  );
}
